### PR TITLE
fix: only serialize JSON bodies

### LINKED ISSUE #58: [BUG] About send a request with body text type
https://github.com/unjs/ohmyfetch/blob/5307000f12ad2414e07f194bb049d78cef654cd4/src/fetch.ts#L108-L109
If I want to send a text body post request, it will `JSON.stringify` my text and add `"` before and after my text.

image

### PR DESCRIPTION
**Pull request by P4sca1**
Previously, everything that looked like it could be serialized, was actually serialized, no matter what content type was set.
This includes arbitrary strings. When you tried to send a string like `key "myval"` to the server using ohmyfetch, the server received `"key \\"myval\\""`.

Closes #58

### CODE REVIEW

File: src/fetch.ts [hunk 1]
```diff
@@ -105,16 +105,23 @@ export function createFetch (globalOptions: CreateFetchOptions): $Fetch {
         ctx.request = withQuery(ctx.request, ctx.options.params)
       }
       if (ctx.options.body && isPayloadMethod(ctx.options.method)) {
+        ctx.options.headers = new Headers(ctx.options.headers)
+
+        // Default to application/json for content-type and accept,
+        // when not explicitly set, and the body is JSON serializable.
         if (isJSONSerializable(ctx.options.body)) {
-          ctx.options.body = JSON.stringify(ctx.options.body)
```
Comment (pi0) [inline src/fetch.ts:109]: Can't we keep check inside this branch?

Comment (P4sca1) [reply src/fetch.ts:109]: Separating the logic to set default headers, from the logic to automatically stringify JSON bodies, makes the code more readable in my opinion.

Comment (pi0) [reply src/fetch.ts:109]: We could directly stringify here but make an exception for type: string. And remove header checking logic.

Comment (P4sca1) [reply src/fetch.ts:109]: Is there any reason to stringify request bodies that have a different content type than application/json?

From my experience, implicitly stringifying leads to more issues than it solves.

Comment (pi0) [reply src/fetch.ts:109]: Probably not. But then what would `options.body` value that is both serializable and we don't intend to serialize?

Comment (P4sca1) [reply src/fetch.ts:109]: For example when you want to send raw strings or numbers that need to be send unmodified to the server.

Comment (pi0) [reply src/fetch.ts:109]: Yes strings should be fixed as is. That's for the linked issue. JSON.stringify on other primitives does nothing. `JSON.stringify(2)` is `2` for instance.

Comment (P4sca1) [reply src/fetch.ts:109]: So, instead of my proposed changes, you want to adjust the `isJSONSerializable` function to return `false` for strings? Is that correct?

Comment (pi0) [reply src/fetch.ts:109]: I would still add application/json as default content type for string body if not specified. We could add a simple inline check like `typeof s === 'string' ? s : JSON.stringify(s)`

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks!
